### ISSUE TITLE
Daylight cycle broken.

### ISSUE THREAD

**Issue by forestg10** [klinbee/Better-Cave-Worlds#3]
I broke bedrock for a mob grinder, but unfortunately the daylight cycle broke. I went into the level.dat and DoDayLightCycle is set to true.

**Comment by klinbee** [comment]
The dimension time is set to always be midnight, so the sky is always dark in the caves. What is the exact issue you are having? How does not having day time negatively impact your mob farms?

**Comment by forestg10** [comment]
> The dimension time is set to always be midnight, so the sky is always dark in the caves. What is the exact issue you are having? How does not having day time negatively impact your mob farms?

Well for one my other cave only world does the day cycle? Secondly its already hard to light up the caves, but now they just spawn on the grond.

**Comment by forestg10** [comment]
![image](https://github.com/user-attachments/assets/e7da14c8-8a09-41a6-b6b0-99b122a9f12c)

**Comment by forestg10** [comment]
freecam btw

**Comment by klinbee** [comment]
How would changing the sky to have daylight fix this? You would run across the same issue the moment it turns night. Besides Mobs can't spawn on Bedrock, so that isn't a negative point either. The biggest contributor to the mob cap issue just will be the caves, which wouldn't be impacted by the day change.

**Comment by forestg10** [comment]
> How would changing the sky to have daylight fix this? You would run across the same issue the moment it turns night, IF that would even help. Mobs can't spawn on Bedrock, so that isn't a negative point either. The biggest contributor to the mob cap issue just will be the caves, which wouldn't be impacted by the day change.

Yes sorry lol i lit up the caves and went to sleep yesterday forgot about that part. Mb

**Comment by forestg10** [comment]
No clue what happened, I didn't touch the mod but day??? 
![image](https://github.com/user-attachments/assets/47312f8f-3157-461c-813e-b8b40e38c9ca)
